### ISSUE TITLE
Do something with fields of Class meta models which has real class

### ISSUE THREAD

**Issue by mikolajmitura** [mikolajmitura/crud-wizard#62]
Fields should be split for read and writes. 
Class metamodels when are loaded should load fields as well. Fields with some overrides should be merged with original fields. 
User cannot add news fields but attach translations, some additional properties or other properties. 
But can be added validation on that fields? Better no.
Should be validation which comes from javax validation and additional validation which can be added in generic endpoint (I don't know that will be working for that case. Additional validation is traversing nodes based on map (maybe) it needs to be checked)

**Comment by mikolajmitura** [comment]
block opportunity for adding extentsion on class metamodel which are based on real class. 
So extends always comes from java inheritance. 
Fetch all fields for read and write should be based on all available fields based on all arg constructor or based on builder. 
When payload is resolved by jackson and have only opportunity for create by builder, super builder or all args then fields from super class will be not added as all fields for write. Verify that how jackson will be resolve that. 
In generated mappers create target objects will be work in this way, so fields for that kind of class metamodel should be work in this way without get all fields from super classes.  
When we want all of that fields (from supper class) maybe necessary will be change in mappers and in jackson resolving json to realClass(in service or mapper input), for example invoking setters or via reflection on field in super classes after invoke builder or all arg constructor inside of mapper. 
Necessary is change in class metamodel on which field resolver are based. (after reload from db)

**Comment by mikolajmitura** [comment]
things to do:

- [x] Fields should be split for read and writes.

- [x] User cannot add news fields but attach translations, some additional properties (cannot add validation)
- [x] block opportunity for adding extentsion on class metamodel which are based on real class
- [x] Additional validation is traversing nodes based on map (maybe) it needs to be checked)
- [x] for front classmetamodel based on real class will be default field resolver for write and read fields. (cannot be changed field resolver like in mappers) during resolving for front object "{}" json should be used for check that given real class can be build upon given class. 
- [x] for fields which have @JsonProperty should be added additional property with value from json property.
